# Generated by Django 2.0.2 on 2018-03-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pref_day',
            field=models.CharField(default='Day of the week', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='pref_time',
            field=models.CharField(default='Time of the Day', max_length=10),
            preserve_default=False,
        ),
    ]
