# Generated by Django 2.0.2 on 2018-03-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180326_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='pref_day',
            new_name='Day',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='decription',
            new_name='Decription',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='pref_time',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='Slug',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='course',
            name='Time',
            field=models.CharField(default='time', max_length=10),
            preserve_default=False,
        ),
    ]
