# Generated by Django 2.0.2 on 2018-03-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180327_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Date',
            new_name='date',
        ),
    ]
