# Generated by Django 2.0.2 on 2018-03-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180327_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Slug',
            new_name='slug',
        ),
    ]
