# Generated by Django 2.0.2 on 2018-03-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180327_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Decription',
            new_name='decription',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Day',
            new_name='pref_day',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Room',
            new_name='pref_time',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Time',
        ),
    ]
