# Generated by Django 2.0.2 on 2018-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180327_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
