# Generated by Django 2.0.2 on 2018-03-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180329_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.CharField(choices=[('HNS 114', 'HNS 114'), ('HNS 108', 'HNS 108'), ('HNS 106', 'HNS 106'), ('HNS E167/168', 'HNS E167/168'), ('HNS E169', 'HNS E169'), ('HNS E170', 'HNS E170')], max_length=20),
        ),
    ]
