# Generated by Django 2.0.2 on 2018-03-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180329_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_room',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
