# Generated by Django 2.0.3 on 2018-04-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('Anthropology', 'Anthropology'), ('Art', 'Art'), ('Art History', 'Art History'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Environmental Studies', 'Environmental Studies'), ('Gender Studies', 'Gender Studies'), ('Geography', 'Geography'), ('History', 'History'), ('Interdivisional', 'Interdivisional'), ('Languages', 'Languages'), ('Literature', 'Literature'), ('Mathematics', 'Mathematics'), ('Music', 'Music'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Religion', 'Religion'), ('Sociology', 'Sociology'), ('Statistics', 'Statistics'), ('Theater', 'Theater'), ('Writing', 'Writing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='ucs_time_date1',
            field=models.CharField(choices=[('MWF9', 'MWF 9:00 - 9:50 AM'), ('MWF10', 'MWF 10:00 - 10:50 AM'), ('MWF11', 'MWF 11:00 - 11:50 AM'), ('MR121', 'MR 12:30 - 1:50 PM'), ('MR23', 'MR 2:00 - 3:20 PM'), ('MR34', 'MR 3:30 - 4:50 PM'), ('MW78', 'MW 7:00 - 8:20 PM'), ('TR910', 'TR 9:00 - 10:20 AM'), ('TR1011', 'TR 10:30 - 11:50 AM'), ('TF12', 'TF 1:00 - 2:20 PM'), ('TF45', 'TF 4:00 - 5:20 PM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='ucs_time_date2',
            field=models.CharField(choices=[('MWF9', 'MWF 9:00 - 9:50 AM'), ('MWF10', 'MWF 10:00 - 10:50 AM'), ('MWF11', 'MWF 11:00 - 11:50 AM'), ('MR121', 'MR 12:30 - 1:50 PM'), ('MR23', 'MR 2:00 - 3:20 PM'), ('MR34', 'MR 3:30 - 4:50 PM'), ('MW78', 'MW 7:00 - 8:20 PM'), ('TR910', 'TR 9:00 - 10:20 AM'), ('TR1011', 'TR 10:30 - 11:50 AM'), ('TF12', 'TF 1:00 - 2:20 PM'), ('TF45', 'TF 4:00 - 5:20 PM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='ucs_time_date3',
            field=models.CharField(choices=[('MWF9', 'MWF 9:00 - 9:50 AM'), ('MWF10', 'MWF 10:00 - 10:50 AM'), ('MWF11', 'MWF 11:00 - 11:50 AM'), ('MR121', 'MR 12:30 - 1:50 PM'), ('MR23', 'MR 2:00 - 3:20 PM'), ('MR34', 'MR 3:30 - 4:50 PM'), ('MW78', 'MW 7:00 - 8:20 PM'), ('TR910', 'TR 9:00 - 10:20 AM'), ('TR1011', 'TR 10:30 - 11:50 AM'), ('TF12', 'TF 1:00 - 2:20 PM'), ('TF45', 'TF 4:00 - 5:20 PM')], max_length=10),
        ),
    ]
