# Generated by Django 2.0.2 on 2018-05-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_enemies'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Class_Size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='cap',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='term_length',
            field=models.CharField(choices=[('', '-----'), ('Full Term', 'Full Term'), ('Mod 1', 'Mod 1'), ('Mod 2', 'Mod 2'), ('Full Term Mod Credit', 'Full Term Mod Credit')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
