# Generated by Django 2.0.3 on 2018-05-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20180419_1745'),
        ('courses', '0019_auto_20180430_1104'),
    ]

    operations = [
    ]
