# Generated by Django 2.0.3 on 2018-05-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_merge_20180501_1258'),
        ('courses', '0020_course_enemies'),
    ]

    operations = [
    ]
