# Generated by Django 2.0.2 on 2018-05-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_merge_20180503_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Class_Size',
        ),
        migrations.AddField(
            model_name='course',
            name='Gender_Studies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='Interdisciplinary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='LAC',
            field=models.BooleanField(default=False),
        ),
    ]
