# Generated by Django 2.0.2 on 2018-05-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20180503_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
