# Generated by Django 2.0.2 on 2018-05-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20180503_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='room3',
            field=models.CharField(choices=[('', '-------'), ('HNS 114', 'HNS 114'), ('HNS 108', 'HNS 108'), ('HNS 106', 'HNS 106'), ('HNS E167/168', 'HNS E167/168'), ('HNS E169', 'HNS E169'), ('HNS E170', 'HNS E170'), ('LBR 156', 'LBR 156'), ('LBR 209', 'LBR 209'), ('LBR 248', 'LBR 248'), ('LBR 259', 'LBR 259'), ('LBR 252', 'LBR 252'), ('HCL 8', 'HCL 8'), ('HCL 7', 'HCL 7'), ('Palmer 211', 'Palmer 211'), ('Palmer 213', 'Palmer 213'), ('MBR 100', 'MBR 100'), ('MBR 113', 'MBR 113'), ('ACE 102', 'ACE 102'), ('ACE 112', 'ACE 112'), ('ACE 113', 'ACE 113'), ('ACE 115', 'ACE 115'), ('ACE 201', 'ACE 201'), ('ACE 210', 'ACE 210'), ('ACE 211', 'ACE 211'), ('ACE 217', 'ACE 217'), ('ACE 218', 'ACE 218'), ('ACE 228', 'ACE 228'), ('ACE 237', 'ACE 237'), ('ACE 239', 'ACE 239'), ('ACE 327', 'ACE 327'), ('ACE 329', 'ACE 329'), ('CH 214', 'CH 214'), ('Bon', 'Bon'), ('Bon Class', 'Bon Class'), ('COH 120', 'COH 120'), ('CGR 103', 'CGR 103')], default=False, max_length=20),
        ),
    ]
