# Generated by Django 2.0.3 on 2018-05-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_course_class_size'),
        ('courses', '0029_auto_20180503_2135'),
    ]

    operations = [
    ]
