# Generated by Django 2.0.2 on 2018-05-04 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_merge_20180503_2145'),
        ('courses', '0030_auto_20180503_2205'),
    ]

    operations = [
    ]
