# Generated by Django 2.0.2 on 2018-03-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
