# Generated by Django 2.0.2 on 2018-03-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pref_day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pref_time',
        ),
        migrations.AddField(
            model_name='course',
            name='ucs_time_date',
            field=models.CharField(choices=[(1, 'MWF8'), (2, 'MWF9'), (3, 'MWF10'), (4, 'MWF11'), (5, 'MR121'), (6, 'MR23'), (7, 'MR34'), (8, 'MW78'), (9, 'TR910'), (10, 'TR1011'), (11, 'TF12'), (12, 'TF45')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
