# Generated by Django 2.0.2 on 2018-04-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science')], default='Computer Science', max_length=30),
            preserve_default=False,
        ),
    ]
