# Generated by Django 2.0.2 on 2018-05-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20180502_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Class_Size',
        ),
    ]
