# Generated by Django 2.0.2 on 2018-05-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_class_size'),
        ('courses', '0022_remove_course_class_size'),
    ]

    operations = [
    ]
