# Generated by Django 2.0.2 on 2018-03-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('assigned_time', models.CharField(max_length=15)),
                ('assigned_room', models.CharField(max_length=20)),
            ],
        ),
    ]
